management.endpoints.web.exposure.include=health,info,metrics
info.application.name=wealth management
info.application.version=1.0
info.application.environment=dev
application.support-email=support@example.com
server.port=8081
management.info.env.enabled=true